server {
    listen 80;
    server_name aduanhub.rekadev.site;
    location ^~ /.well-known/acme-challenge/ { root /var/www/rekadev-acme; default_type text/plain; }
    location / { proxy_pass http://127.0.0.1:18083; include proxy_params; proxy_set_header X-Forwarded-Proto $scheme; }
}
