name: Android release

concurrency:
  group: android-release
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "mobile/**"
      - ".github/workflows/android.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed lib test
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --release --dart-define=API_BASE_URL=https://aduanhub.rekadev.site/api/v1
      - uses: actions/upload-artifact@v4
        with:
          name: AduanHub-Android-1.0.0
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          retention-days: 30
